version: 2.1

orbs:
  bitcartcc: bitcartcc/bitcartcc-shared@1

jobs:
  # publish jobs require $DOCKER_USER, $DOCKER_PASS defined
  publish_linuxamd64:
    executor: bitcartcc/build-ubuntu
    steps:
      - checkout
      - bitcartcc/login-to-registries
      - run:
          command: |
            source ".circleci/parse-tag.sh"
            DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_AMD64"
            DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG-amd64"
            if [ -f $DOCKERHUB_DOCKEFILE ]; then
                source ".circleci/push-image.sh"
            else
                echo "Skipping linuxamd64 because $DOCKERHUB_DOCKEFILE is not found"
            fi

  publish_linuxarm64v8:
    executor: bitcartcc/build-ubuntu
    steps:
      - checkout
      - bitcartcc/login-to-registries
      - run:
          command: |
            source ".circleci/parse-tag.sh"
            DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_ARM64"
            DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG-arm64v8"
            if [ -f $DOCKERHUB_DOCKEFILE ]; then
                docker run --privileged --rm multiarch/qemu-user-static:register --reset
                source ".circleci/push-image.sh"
            else
                echo "Skipping linuxarm64v8 because $DOCKERHUB_DOCKEFILE is not found"
            fi

  publish_multiarch:
    executor: bitcartcc/build-ubuntu
    steps:
      - checkout
      - bitcartcc/login-to-registries
      - run:
          command: |
            source ".circleci/parse-tag.sh"
            publish_manifest ""
            publish_manifest "ghcr.io/"
            publish_manifest "harbor.nirvati.org/"

workflows:
  version: 2
  publish:
    jobs:
      - publish_linuxamd64:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[^/]+[/][0-9]+(\.[0-9]+)*(-[a-z0-9\.-]+)?/
      - publish_linuxarm64v8:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[^/]+[/][0-9]+(\.[0-9]+)*(-[a-z0-9\.-]+)?/
      - publish_multiarch:
          requires:
            - publish_linuxamd64
            - publish_linuxarm64v8
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[^/]+[/][0-9]+(\.[0-9]+)*(-[a-z0-9\.-]+)?/
