#!/bin/bash

SEPARATOR=$(expr index "$CIRCLE_TAG" "/")
NODE_NAME=${CIRCLE_TAG:0:$SEPARATOR-1}
REVISION=""
NODE_VERSION="${CIRCLE_TAG:$SEPARATOR}"
if expr index "$NODE_VERSION" "-" >/dev/null; then
    SEPARATOR_REVISION=$(expr index "$NODE_VERSION" "-")
    REVISION="${NODE_VERSION:$SEPARATOR_REVISION}"
    NODE_VERSION="${NODE_VERSION:$SEPARATOR:$SEPARATOR_REVISION-$SEPARATOR-1}"
fi
LATEST_TAG="${CIRCLE_TAG:$SEPARATOR}"
DOCKERHUB_REPO="bitcart/$NODE_NAME"
DOCKERHUB_REPO="${DOCKERHUB_REPO,,}"
DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG"
DOCKERHUB_DOCKEFILE_ARM64="$NODE_NAME/linuxarm64v8.Dockerfile"
DOCKERHUB_DOCKEFILE_AMD64="$NODE_NAME/linuxamd64.Dockerfile"

echo "LATEST_TAG=$LATEST_TAG"
echo "NODE_VERSION=$NODE_VERSION"
echo "REVISION=$REVISION"
echo "DOCKERHUB_REPO=$DOCKERHUB_REPO"
echo "DOCKERHUB_DESTINATION=$DOCKERHUB_DESTINATION"
echo "DOCKERHUB_DOCKEFILE_AMD64=$DOCKERHUB_DOCKEFILE_AMD64"
echo "DOCKERHUB_DOCKEFILE_ARM64=$DOCKERHUB_DOCKEFILE_ARM64"

publish_manifest() {
    IMAGES=""
    if [ -f $DOCKERHUB_DOCKEFILE_AMD64 ]; then
        IMAGES="$IMAGES $1$DOCKERHUB_DESTINATION-amd64"
    fi
    if [ -f $DOCKERHUB_DOCKEFILE_ARM64 ]; then
        IMAGES="$IMAGES $1$DOCKERHUB_DESTINATION-arm64v8"
    fi
    if [ -z "$IMAGES" ]; then
        echo "Skipping $1$DOCKERHUB_DESTINATION as there were no supported platforms to build for"
    else
        docker manifest create --amend $1$DOCKERHUB_DESTINATION $IMAGES
        if [ -f $DOCKERHUB_DOCKEFILE_AMD64 ]; then
            docker manifest annotate $1$DOCKERHUB_DESTINATION $1$DOCKERHUB_DESTINATION-amd64 --os linux --arch amd64
        fi
        if [ -f $DOCKERHUB_DOCKEFILE_ARM64 ]; then
            docker manifest annotate $1$DOCKERHUB_DESTINATION $1$DOCKERHUB_DESTINATION-arm64v8 --os linux --arch arm64 --variant v8
        fi
        docker manifest push $1$DOCKERHUB_DESTINATION -p
    fi
}
